from app.models.aprobacionevento import AprobacionEventoModel
from app.models.secretariaacademica import SecretariaAcademicaModel
from app.models.aprobacionevento import AprobacionEventoModel
from app.models.instalacion import InstalacionModel
from app.models.persona import PersonaModel
from app.models.director import DirectorModel
from app.models.docente import DocenteModel
from app.models.estudiante import EstudianteModel
from app.models.evento import EventoModel
from app.models.facultad import FacultadModel
from app.models.historialcontrasenas import HistorialContrasenasModel
from app.models.organizacion import OrganizacionModel
from app.models.organizacionparticipacion import OrganizacionParticipacionModel
from app.models.participacion import ParticipacionModel
from app.models.unidad import UnidadModel